version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/postgre
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  etl:
    build: ./etl
    volumes:
      - ./etl/hop-project:/project
      - ./outputs:/outputs
    depends_on:
      - db
    command: hop-run.sh -p pandemie -f pipelines/pipeline1.hpl -e dev

volumes:
  postgres-data:
